import { NextResponse } from "next/server";
import { createServerSupabaseClient, createServiceRoleClient } from "@/lib/supabase/server";

interface AchievementDef {
  key: string;
  label: string;
  description: string;
  cta_label?: string;
  cta_href?: string;
}

const ALL_ACHIEVEMENTS: AchievementDef[] = [
  { key: "account_created", label: "Created your account", description: "Welcome to AnyVision!" },
  { key: "profile_completed", label: "Completed business profile", description: "Tell us about your business", cta_label: "Complete profile", cta_href: "/portal/settings" },
  { key: "first_connection", label: "Connected first integration", description: "Link your business tools", cta_label: "Connect now", cta_href: "/portal/connections" },
  { key: "first_workflow", label: "Activated first workflow", description: "Set up an automation", cta_label: "Browse workflows", cta_href: "/portal/workflows" },
  { key: "first_execution", label: "First automation ran", description: "Your automation executed successfully" },
  { key: "first_lead", label: "Captured first lead", description: "A lead was generated by your automations" },
];

export async function GET() {
  const supabase = await createServerSupabaseClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const svc = await createServiceRoleClient();

  const { data: client } = await svc
    .from("clients")
    .select("id")
    .eq("auth_user_id", user.id)
    .single();

  if (!client) {
    return NextResponse.json({ error: "Client not found" }, { status: 404 });
  }

  // Fetch achieved items
  const { data: achieved } = await svc
    .from("client_achievements")
    .select("achievement_key, achieved_at")
    .eq("client_id", client.id);

  const achievedKeys = new Set((achieved || []).map((a) => a.achievement_key));
  const achievedMap = new Map(
    (achieved || []).map((a) => [a.achievement_key, a.achieved_at])
  );

  // Build response with unlocked/locked status
  const achievements = ALL_ACHIEVEMENTS.map((def) => ({
    ...def,
    achieved: achievedKeys.has(def.key),
    achieved_at: achievedMap.get(def.key) || null,
  }));

  const totalCount = ALL_ACHIEVEMENTS.length;
  const achievedCount = achievedKeys.size;

  return NextResponse.json({
    achievements,
    total: totalCount,
    achieved: achievedCount,
    progress_pct: Math.round((achievedCount / totalCount) * 100),
  });
}
