"""Generate a CSV of the 20 Tier 3 priority candidates for Airtable bulk import.

Outputs `workflows/linkedin-dept/tier3-import.csv` — drag-drop into Airtable's
`LI_Leads` table via the UI (Add records → Import data → CSV).

Expands on Tier 2: broader industry coverage (insurtech, healthcare PM, HR tech,
cybersecurity, Nigeria, Kenya, US post-exit advisors). All 20 records have at
least a named founder. LinkedIn URL is verified where available; remaining ones
require a ~5-min manual LinkedIn lookup before send.

Usage:
    python tools/generate_tier3_csv.py
"""

from __future__ import annotations

import csv
import json
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s", datefmt="%H:%M:%S")
log = logging.getLogger("csv_gen_t3")

OUTPUT = Path(__file__).parent.parent / "workflows" / "linkedin-dept" / "tier3-import.csv"

FIELDS = [
    "Lead ID",
    "Full Name",
    "First Name",
    "Last Name",
    "Title",
    "Company Name",
    "Industry",
    "Location",
    "LinkedIn URL",
    "Company Website",
    "Employee Count",
    "Source",
    "Status",
    "POPIA Consent",
    "Source Metadata",
]


def m(**kwargs) -> str:
    return json.dumps(kwargs, separators=(",", ":"))


RECORDS = [
    # ============ CONFIRMED LINKEDIN (7 records) — highest quality, send-ready ============
    {
        "Lead ID": "LI-PRIORITY-T3-018",
        "Full Name": "Luis da Silva",
        "First Name": "Luis",
        "Last Name": "da Silva",
        "Title": "CEO & Managing Director",
        "Company Name": "Healthbridge",
        "Industry": "Healthcare Tech (Medical Billing + Practice Management)",
        "Location": "South Africa",
        "LinkedIn URL": "https://www.linkedin.com/in/luis-da-silva-b037a84/",
        "Company Website": "https://healthbridge.co.za",
        "Employee Count": "50-150",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="medium",
            linkedin_quality="verified",
            background="CEO since May 2007. BSc Electrical Engineering (distinction) Wits 1990 + MBA Wits. Joined Healthbridge 2000 as Key Accounts Exec.",
            scale="5,000+ doctors across SA. Pioneered real-time medical claim processing since early 2000s.",
            founder_original="Gregory VandenBosch (now at HealthBridge.ai potentially separate venture)",
            hook="established_saas_scaling_digital_transformation",
            pain_hypothesis="5,000 doctor accounts = massive data pipeline needs. Healthbridge does medical billing + EMR. AVM can offer: competitor medical PM monitoring, automated ICD-10 code compliance checks, medical aid scheme scraping for rate changes.",
            pitch_angle="Wits engineer + MBA - speaks both tech and business. Frame as scale-up infrastructure.",
            verification_needed=["recent_post", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-019",
        "Full Name": "Kobus Wolvaardt",
        "First Name": "Kobus",
        "Last Name": "Wolvaardt",
        "Title": "CEO",
        "Company Name": "GoodX Software",
        "Industry": "Healthcare Tech (Practice Management)",
        "Location": "Pretoria, Gauteng, South Africa",
        "LinkedIn URL": "https://za.linkedin.com/in/kobus-wolvaardt-318736189",
        "Company Website": "https://goodx.co.za",
        "Employee Count": "80-150",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="medium",
            linkedin_quality="verified",
            founder_original="Dr Dirkie Wolvaardt (founded 1985, 40 years heritage)",
            relationship_to_founder="Likely son / family succession - Kobus now leads growth",
            scale="80+ employees, trusted by practitioners across Southern Africa",
            product_line="GoodX Web, myGC, GoodX Switch",
            hook="40_year_incumbent_needs_modern_data_layer",
            pain_hypothesis="40yr heritage = legacy data models. They service Southern Africa practitioners. AVM can offer: migration tooling from legacy systems, modernized reporting pipelines, competitor PM monitoring.",
            pitch_angle="Family-business CEO - relationship-first language. Respect the 40yr legacy in the opener.",
            verification_needed=["recent_post", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-020",
        "Full Name": "Simon Ellis",
        "First Name": "Simon",
        "Last Name": "Ellis",
        "Title": "Co-Founder & CEO",
        "Company Name": "Jem HR",
        "Industry": "HR Tech (WhatsApp-based HR for frontline workers)",
        "Location": "Cape Town, South Africa",
        "LinkedIn URL": "https://za.linkedin.com/in/simon-reid-ellis",
        "Company Website": "https://www.jemhr.com",
        "Employee Count": "20-50",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="high",
            linkedin_quality="verified",
            co_founders=["Alex Platt", "Caroline van der Merwe", "Nick Platt"],
            background="CA(SA) - Chartered Accountant",
            founded="2019 as SmartWage, rebranded Jem 2022",
            funding="$3.3M (R60M) pre-Series A Mar 2025 - led by Next176 (Old Mutual subsidiary)",
            scale="Serves companies with deskless/frontline workers via WhatsApp - no app download required",
            recent_signal="Oct 2025 - launched mobile service to cut data costs for SA frontline workers",
            hook="just_funded_scaling_phase_tooling_gap",
            pain_hypothesis="Pre-Series A raised Mar 2025 = 12+ months of runway deployment. WhatsApp-first HR means fragmented data pipelines (WhatsApp conversation logs, payroll systems, benefits platforms). AVM can offer: conversation analytics, client sentiment tracking, competitor frontline-HR tool monitoring.",
            pitch_angle="CA founder - ROI math + compliance language. WhatsApp-first = unique data footprint to exploit.",
            verification_needed=["recent_post", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-021",
        "Full Name": "Yvonne Johnson",
        "First Name": "Yvonne",
        "Last Name": "Johnson",
        "Title": "Co-Founder & MD",
        "Company Name": "Indicina",
        "Industry": "Fintech Infrastructure (Credit Decisioning ML)",
        "Location": "Lagos, Nigeria",
        "LinkedIn URL": "https://ng.linkedin.com/in/yvonneoyetakin",
        "Company Website": "https://indicina.co",
        "Employee Count": "20-80",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="medium",
            linkedin_quality="verified",
            co_founder="Yemi Ajao",
            education="BSc Computer Science + Math University of Toronto; MBA Northwestern Kellogg (honors)",
            prior_experience="8 years First Bank of Nigeria - Head of Strategy and Corporate Development",
            founded=2018,
            funding="$3M raised (Crunchbase + Itanna $150K seed)",
            scale="ML-powered credit decision platform for African lenders",
            notable_investor_connections="Early-stage investor/advisor in Andela, Flutterwave",
            hook="ai_native_fintech_needs_data_infrastructure",
            pain_hypothesis="Already uses ML for credit decisioning. Like Naked/BriefCo - pitch DATA not AI. Sub-Saharan Africa credit data is fragmented: public registries, telco data, social signals. AVM can scrape + structure at scale.",
            pitch_angle="Kellogg MBA + SWE background = speaks both sides. Reference her Andela/Flutterwave network as social proof that AVM understands her world.",
            verification_needed=["recent_post", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-022",
        "Full Name": "Nithen Naidoo",
        "First Name": "Nithen",
        "Last Name": "Naidoo",
        "Title": "Founder & CEO",
        "Company Name": "Snode Technologies",
        "Industry": "Cybersecurity",
        "Location": "South Africa",
        "LinkedIn URL": "https://za.linkedin.com/in/nithen",
        "Company Website": "https://www.snode.com",
        "Employee Count": "10-50",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="low",
            linkedin_quality="verified",
            hook="cybersecurity_smb_needs_threat_intel_scraping",
            pain_hypothesis="Cybersecurity shops need continuous threat intel feeds. AVM can offer: dark web mention scraping for clients, CVE feed aggregation + priority scoring, competitor security-vendor monitoring.",
            pitch_angle="Security founder - speak threats + infrastructure. Avoid buzzwords, lead with specific threat-type pipelines.",
            verification_needed=["recent_post", "email", "company_size_employee_count_confirm", "website_url_verify"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-023",
        "Full Name": "Ben Lyon",
        "First Name": "Ben",
        "Last Name": "Lyon",
        "Title": "Co-Founder (Kopo Kopo acquired by Moniepoint 2023)",
        "Company Name": "Hover / Kopo Kopo alumnus",
        "Industry": "Fintech (Mobile Money / Payments)",
        "Location": "Kenya / US",
        "LinkedIn URL": "https://www.linkedin.com/in/bmlyon",
        "Company Website": "https://useHover.com",
        "Employee Count": "5-30",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="relationship_intro",
            urgency="low",
            linkedin_quality="verified",
            relationship_type="ADVISOR/INTRO TARGET not direct pitch - Kopo Kopo acquired by Moniepoint Aug 2023",
            current_ventures="Hover (co-founder), Caribou Digital's DFS Lab (entrepreneur-in-residence)",
            background="Fintech founder with Africa/Asia mobile money expertise - sourced fintech startups across emerging markets",
            value_proposition="Not a direct buyer. Build relationship for intros to mobile money / emerging markets fintech shops that ARE buyers.",
            hook="warm_intro_into_african_fintech_network",
            pitch_angle="Peer-to-peer, NOT sales. 'Saw Kopo Kopo's Moniepoint exit - building Apify+Claude pipelines for African fintech. Would love your perspective on where data infrastructure is most underdeveloped in the ecosystem.' Consultative ask.",
            verification_needed=["recent_post", "current_role_confirmation"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-024",
        "Full Name": "Ryan Hogan",
        "First Name": "Ryan",
        "Last Name": "Hogan",
        "Title": "Founder (Hunt A Killer - acquired)",
        "Company Name": "Hunt A Killer alumnus",
        "Industry": "Subscription DTC (post-acquisition)",
        "Location": "Los Angeles, United States",
        "LinkedIn URL": "https://www.linkedin.com/in/ryanehogan/",
        "Company Website": "https://ryanehogan.com",
        "Employee Count": "1-10",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="relationship_intro",
            urgency="low",
            linkedin_quality="verified",
            relationship_type="ADVISOR/INTRO TARGET - Hunt A Killer was acquired, Ryan now LinkedIn bio says 'Founder of Hunt A Killer (acquired)'",
            prior_co_founder="Derrick Smith",
            scale_at_exit="INC #1 fastest-growing subscription DTC brand from zero",
            current_status="Post-exit - likely angel investing, advising, or building next venture",
            value_proposition="Warm intro potential to subscription DTC network. Also interesting case study for Eric Carlson (LI-PRIORITY-005) since Sweat Pants Agency worked with Hunt A Killer.",
            hook="connect_to_subscription_dtc_network_and_possible_angel",
            pitch_angle="Ask for 15 min 'picking your brain on subscription DTC data tooling, where's the real gap a boutique build shop could fill.' Consultative, not sales. May lead to intros to other DTC founders.",
            verification_needed=["current_building_status", "available_for_cold_outreach"],
        ),
    },
    # ============ NAMED FOUNDER, LINKEDIN TBD (7 records) — 5-min lookup before send ============
    {
        "Lead ID": "LI-PRIORITY-T3-025",
        "Full Name": "Mark Novitzkas",
        "First Name": "Mark",
        "Last Name": "Novitzkas",
        "Title": "Founder & CTO",
        "Company Name": "Navitas Concepts",
        "Industry": "Healthcare Tech (Allied/Auxiliary Practice Management SaaS)",
        "Location": "Cape Town, South Africa",
        "LinkedIn URL": "",
        "Company Website": "https://www.navitas.co.za",
        "Employee Count": "5-20",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="medium",
            linkedin_quality="TBD - search 'Mark Novitzkas Navitas' on LinkedIn before send",
            founder_background="Avid Python developer 13+ years experience. Partner runs acupuncture practice (inspiration for Navitas)",
            founded=2015,
            product="Only SA subscription SaaS for allied/auxiliary health medical professionals. Navitas Green (basic) + Navitas Gold (customizable)",
            hook="python_founder_cto_needs_data_pipeline_tooling",
            pain_hypothesis="Technical solo-CTO founder in a niche vertical. Small team. AVM can offer: automated competitor research, client onboarding automation, subscription churn analysis tooling.",
            pitch_angle="Python-to-Python language. 'Same stack philosophy, outsourced.' Small founder = sensitive to pricing, lead with low-commitment POC.",
            verification_needed=["linkedin_url_manual", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-026",
        "Full Name": "Caroline van der Merwe",
        "First Name": "Caroline",
        "Last Name": "van der Merwe",
        "Title": "Co-Founder & CPO",
        "Company Name": "Jem HR",
        "Industry": "HR Tech (WhatsApp-based HR)",
        "Location": "Cape Town, South Africa",
        "LinkedIn URL": "",
        "Company Website": "https://www.jemhr.com",
        "Employee Count": "20-50",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="low",
            linkedin_quality="TBD - search 'Caroline van der Merwe Jem' on LinkedIn",
            parallel_to="LI-PRIORITY-T3-020 (Simon Ellis, same company)",
            multi_thread_gating="Conditional - only send if Simon silent 14+ days",
            role="Chief Product Officer - product/user experience focus",
            hook="product_angle_at_jem_not_strategic",
            pain_hypothesis="Same company as Simon but Caroline = product-side. Pitch user analytics / sentiment / feature-adoption tooling specifically, not strategic BD plays.",
            verification_needed=["linkedin_url_manual", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-027",
        "Full Name": "Gabriel Ruhan",
        "First Name": "Gabriel",
        "Last Name": "Ruhan",
        "Title": "CEO",
        "Company Name": "Paycode",
        "Industry": "Fintech + Biometric Identity (Financial Inclusion)",
        "Location": "Cape Town, South Africa",
        "LinkedIn URL": "",
        "Company Website": "https://www.paycode.com",
        "Employee Count": "30-100",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="medium",
            linkedin_quality="TBD - search 'Gabriel Ruhan Paycode' on LinkedIn",
            funding="$15M Series A stage",
            product="Biometric digital identity + payments for unbanked. Central Bank Digital Currency (CBDC) solution.",
            market="Unbanked populations, African financial inclusion",
            hook="scaling_fintech_regulatory_intel_gap",
            pain_hypothesis="Biometric identity + CBDC = heavy regulatory burden (FSCA, SARB, Central Banks across Africa). AVM can offer: regulatory intel scraping per country (FSCA, SARB, Kenya CBK, Ghana BOG), competitor CBDC vendor monitoring, policy shift alerting.",
            pitch_angle="Regulated fintech at scale - compliance language. 'Data infrastructure for policy tracking across your target markets.'",
            verification_needed=["linkedin_url_manual", "email", "employee_count_verify"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-028",
        "Full Name": "Jorn Das",
        "First Name": "Jorn",
        "Last Name": "Das",
        "Title": "Co-Lead",
        "Company Name": "Gravit8 IT",
        "Industry": "Cybersecurity + Managed IT (MSSP)",
        "Location": "Cape Town + Johannesburg, South Africa",
        "LinkedIn URL": "",
        "Company Website": "https://www.gravit8.co.za",
        "Employee Count": "10-50",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="medium",
            linkedin_quality="TBD - search 'Jorn Das Gravit8' on LinkedIn",
            co_lead="Gary Fouchè",
            founded=2004,
            scale="Over a decade in SMME market, multi-city (CT + JHB)",
            positioning="MSSP for small/medium SA companies - understands SMME budget constraints",
            hook="mssp_needs_threat_intel_scraping_at_scale",
            pain_hypothesis="Gravit8 serves 100s of SMMEs. Each needs current threat intel. Manual curation doesn't scale. AVM can offer: client-specific threat intel feeds (industry + geo), CVE prioritization pipelines, automated security reports per client.",
            pitch_angle="MSSP operator - ROI math language. 'Replace 40 hours/month of manual threat intel curation with automation.'",
            verification_needed=["linkedin_url_manual", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-029",
        "Full Name": "Ananth Raj Gudipati",
        "First Name": "Ananth",
        "Last Name": "Gudipati",
        "Title": "Co-Founder",
        "Company Name": "Sukhiba",
        "Industry": "Agritech (Community Commerce Platform)",
        "Location": "Nairobi, Kenya",
        "LinkedIn URL": "",
        "Company Website": "https://www.sukhiba.com",
        "Employee Count": "10-30",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="low",
            linkedin_quality="TBD - search 'Ananth Gudipati Sukhiba' on LinkedIn",
            co_founder="Abhinav Reddy",
            founded=2021,
            accelerator="Google for Startups Accelerator Africa Class 7 (2023)",
            product="Decentralized community-based commerce for farmers",
            hook="agritech_ecommerce_needs_market_intel_scraping",
            pain_hypothesis="Farmer commerce platforms compete with traditional middlemen. Price transparency is the edge. AVM can scrape regional commodity prices + weather data + competitor middleman rates to surface to farmers in-app.",
            pitch_angle="Young startup + Indian co-founders in Kenya = technical + international. Lead with data advantage as differentiation.",
            verification_needed=["linkedin_url_manual", "email", "website_url_confirm"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-030",
        "Full Name": "Gregory VandenBosch",
        "First Name": "Gregory",
        "Last Name": "VandenBosch",
        "Title": "Founder & CEO",
        "Company Name": "HealthBridge AI",
        "Industry": "Healthcare Tech (AI - different from Healthbridge practice mgmt)",
        "Location": "South Africa",
        "LinkedIn URL": "https://www.linkedin.com/in/gregory-vandenbosch-5063035/",
        "Company Website": "",
        "Employee Count": "1-20",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="low",
            linkedin_quality="verified",
            disambiguation="Gregory is at HealthBridge AI - likely different entity from Healthbridge (medical billing). May be a newer venture. Verify.",
            relationship_note="Not a multi-thread to T3-018 Luis da Silva - different company apparently",
            hook="ai_healthcare_startup_scaling",
            pain_hypothesis="Early-stage AI healthcare founder - classic AVM fit: has AI brain, needs data pipeline.",
            pitch_angle="Verify the company scope first. If separate from Healthbridge, pitch as data-infrastructure peer.",
            verification_needed=["company_scope_clarification", "website_url", "employee_count", "email"],
        ),
    },
    # ============ COMPANY-LEVEL CONTEXT RECORDS (6) — founder needs manual lookup ============
    # These were mentioned in research but don't have a named founder yet. Ian should look up
    # the founder on LinkedIn company page before treating these as active pipeline.
    {
        "Lead ID": "LI-PRIORITY-T3-031",
        "Full Name": "TBD - Omniretail Founder",
        "First Name": "TBD",
        "Last Name": "TBD",
        "Title": "Founder",
        "Company Name": "Omniretail",
        "Industry": "B2B Retail Marketplace (Informal Retailers)",
        "Location": "Lagos, Nigeria (operations Nigeria + Ghana + Ivory Coast)",
        "LinkedIn URL": "https://www.linkedin.com/company/omniretail",
        "Company Website": "https://omniretail.africa",
        "Employee Count": "50-200",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="low",
            linkedin_quality="COMPANY_PAGE_ONLY - founder name requires manual lookup",
            founded=2019,
            scale="150,000+ informal retailers across 12 cities (NG, GH, CI)",
            positioning="Network of networks for informal retail - inventory + financing + insurance",
            hook="b2b_marketplace_scaling_data_needs",
            pain_hypothesis="Marketplace with 150K retailers = massive product catalog + pricing data. AVM can offer: competitor marketplace monitoring, demand prediction per SKU per region, FX-adjusted pricing intelligence across 3 countries.",
            pitch_angle="High-volume B2B ops leader - ROI at marketplace scale. Do NOT send until founder name verified.",
            verification_needed=["founder_name_via_linkedin_company_page", "linkedin_url", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-032",
        "Full Name": "TBD - Pastel Founder",
        "First Name": "TBD",
        "Last Name": "TBD",
        "Title": "Founder",
        "Company Name": "Pastel",
        "Industry": "AI Fraud Detection (Enterprise AI)",
        "Location": "Nigeria",
        "LinkedIn URL": "",
        "Company Website": "",
        "Employee Count": "5-30",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="medium",
            linkedin_quality="TBD - search 'Pastel Nigeria AI fraud' on LinkedIn",
            accelerator="Google for Startups Accelerator Africa Class 9 (2025)",
            product="Enterprise AI for fraud detection + anti-money laundering for African financial institutions",
            hook="ai_native_african_fintech_needs_data_feeds",
            pain_hypothesis="Fraud detection AI is only as good as transaction pattern data. AVM can offer: multi-bank fraud pattern pooling pipelines, regulatory filing scraping across African central banks.",
            pitch_angle="Do NOT send until founder verified - company page or recent news article should name them. Google Accelerator Class 9 announcement may have full founder list.",
            verification_needed=["founder_name", "linkedin_url", "website_url", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-033",
        "Full Name": "TBD - Scandium Founder",
        "First Name": "TBD",
        "Last Name": "TBD",
        "Title": "Founder",
        "Company Name": "Scandium",
        "Industry": "Dev Tools (AI QA Automation)",
        "Location": "Nigeria",
        "LinkedIn URL": "",
        "Company Website": "",
        "Employee Count": "5-20",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="low",
            linkedin_quality="TBD",
            accelerator="Google for Startups Accelerator Africa Class 9",
            product="AI Quality Assurance suite - end-to-end test automation + test ops tooling",
            hook="dev_tools_startup_peer",
            pain_hypothesis="AI QA tooling is itself a data problem - needs failure pattern corpus. AVM could partner on test corpus generation from scraped public software bug databases.",
            pitch_angle="Technical dev-tools founder - peer language. Skip unless founder name found.",
            verification_needed=["founder_name", "linkedin_url", "website_url"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-034",
        "Full Name": "TBD - Simply Founder",
        "First Name": "TBD",
        "Last Name": "TBD",
        "Title": "Founder",
        "Company Name": "Simply",
        "Industry": "Life Insurance / Insurtech",
        "Location": "South Africa",
        "LinkedIn URL": "https://za.linkedin.com/company/simplyfs",
        "Company Website": "",
        "Employee Count": "30-100",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="low",
            linkedin_quality="COMPANY_PAGE_ONLY",
            founded=2015,
            mission="Secure the financial futures of millions",
            positioning="Disrupts life insurance via digital buying + broker platforms",
            hook="life_insurance_digitizer_data_pipeline_needs",
            pain_hypothesis="Digital life insurance = heavy underwriting data needs. AVM can offer: medical aid scheme scraping, mortality stats pipelines, competitor policy pricing intel.",
            pitch_angle="Verify founder name first - likely Anthony Miller or Simon Nicholson per some sources, unverified.",
            verification_needed=["founder_name_confirm", "linkedin_url", "website_url", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-035",
        "Full Name": "TBD - Inclusivity Solutions Founder",
        "First Name": "TBD",
        "Last Name": "TBD",
        "Title": "Founder",
        "Company Name": "Inclusivity Solutions",
        "Industry": "Insurtech (Mobile-based Emerging Market Insurance)",
        "Location": "South Africa",
        "LinkedIn URL": "",
        "Company Website": "https://inclusivitysolutions.com",
        "Employee Count": "10-50",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="low",
            linkedin_quality="TBD",
            product="Digital insurance solutions for financial inclusion in emerging markets",
            partners="Mobile operators, banks, insurance companies, financial institutions",
            hook="mobile_insurance_at_emerging_market_scale",
            pain_hypothesis="Mobile operator partnerships require data integration with telco systems + insurance pricing. AVM can offer: telco usage pattern analysis, cross-border regulatory intel, partner performance tracking.",
            pitch_angle="Verify founder first. Social-impact angle matters - lead with financial inclusion outcomes not just revenue.",
            verification_needed=["founder_name", "linkedin_url", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-036",
        "Full Name": "TBD - Leta Founder",
        "First Name": "TBD",
        "Last Name": "TBD",
        "Title": "Founder",
        "Company Name": "Leta",
        "Industry": "Logistics Optimization + Embedded Finance",
        "Location": "Nairobi, Kenya",
        "LinkedIn URL": "https://www.linkedin.com/company/letadelivery",
        "Company Website": "",
        "Employee Count": "20-60",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="low",
            linkedin_quality="COMPANY_PAGE_ONLY",
            funding="$8M+ raised incl Google Africa Investment Fund + Speedinvest",
            product="Logistics optimization + embedded finance for African supply chains",
            hook="logistics_optimization_at_scale_data_layer",
            pain_hypothesis="Route optimization + embedded lending both depend on transaction pattern data. AVM can offer: route history pattern mining, driver risk scoring, competitor last-mile tracking.",
            pitch_angle="Google-backed logistics = credible scale. Lead with supply chain data math.",
            verification_needed=["founder_name", "linkedin_url", "website_url", "email"],
        ),
    },
    # ============ SA BOUTIQUE DIGITAL/CREATIVE AGENCIES (4 records) — company-level ============
    {
        "Lead ID": "LI-PRIORITY-T3-037",
        "Full Name": "TBD - Digital Fox Founder",
        "First Name": "TBD",
        "Last Name": "TBD",
        "Title": "Founder",
        "Company Name": "Digital Fox",
        "Industry": "Digital Marketing Agency (German/SA)",
        "Location": "Cape Town, South Africa",
        "LinkedIn URL": "",
        "Company Website": "",
        "Employee Count": "14",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="low",
            linkedin_quality="TBD",
            size_verified="14 specialists per search result",
            positioning="German/SA agency - PPC + organic marketing",
            hook="small_agency_retainer_expansion_same_as_mo_agency",
            pain_hypothesis="Same pitch as MO Agency (LI-PRIORITY-003) - competitor monitoring + AEO citation tracking as retainer expansion. Smaller than MO so lower commercial ceiling but shorter sales cycle.",
            pitch_angle="Reuse MO Agency pitch template with 'agency owner' adjustment. DO NOT send same week as MO Agency interaction.",
            verification_needed=["founder_name", "linkedin_url", "website_url", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-038",
        "Full Name": "TBD - Mustard Agency Founder",
        "First Name": "TBD",
        "Last Name": "TBD",
        "Title": "Founder",
        "Company Name": "Mustard Agency",
        "Industry": "Creative + Digital Agency",
        "Location": "South Africa",
        "LinkedIn URL": "",
        "Company Website": "https://mustard.agency",
        "Employee Count": "10-50",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="low",
            linkedin_quality="TBD",
            hook="creative_digital_agency_automation_pitch",
            pain_hypothesis="Same family of agency retainer-expansion pitches. Creative agencies especially feel the 'competitive radar' hook because creative trends move faster than SEO.",
            pitch_angle="Verify founder first. Creative-agency language: trend tracking, brand monitoring, creative benchmark scraping.",
            verification_needed=["founder_name", "linkedin_url", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-039",
        "Full Name": "TBD - Trimoon Agency Founder",
        "First Name": "TBD",
        "Last Name": "TBD",
        "Title": "Founder",
        "Company Name": "Trimoon",
        "Industry": "Boutique Digital Agency",
        "Location": "Cape Town, South Africa",
        "LinkedIn URL": "",
        "Company Website": "",
        "Employee Count": "5-20",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="low",
            linkedin_quality="TBD",
            positioning="Boutique CT - 'make all your digital needs effortless'",
            hook="small_boutique_needs_leverage",
            pain_hypothesis="Small agency = founder-operator probably doing everything. AVM automation is a force multiplier for them specifically. Retainer expansion or internal tooling - depends on founder's focus.",
            pitch_angle="Small shop empathy. 'I know you don't have a week to evaluate vendors - here's the 3-min Loom.' Low-friction.",
            verification_needed=["founder_name", "linkedin_url", "website_url", "email"],
        ),
    },
    {
        "Lead ID": "LI-PRIORITY-T3-040",
        "Full Name": "TBD - Indwe Risk Services Founder/MD",
        "First Name": "TBD",
        "Last Name": "TBD",
        "Title": "MD or CEO",
        "Company Name": "Indwe Risk Services",
        "Industry": "Insurance Broker (Established - 120K+ policyholders)",
        "Location": "South Africa",
        "LinkedIn URL": "",
        "Company Website": "https://indwe.co.za",
        "Employee Count": "100-300",
        "Source": "CSV_Upload",
        "Status": "New",
        "POPIA Consent": "Pending",
        "Source Metadata": m(
            tier=3,
            priority=True,
            motion="cold_outreach",
            urgency="medium",
            linkedin_quality="COMPANY_PAGE_LOOKUP",
            scale="120,000+ policyholders",
            positioning="Established broker - tailored services + efficient claims + professional risk analysis",
            hook="established_broker_client_retention_upsell",
            pain_hypothesis="120K policyholders = retention math game. Each 1% retention improvement = massive revenue. AVM can offer: client churn prediction, renewal-cycle outreach automation, competitor broker pricing monitoring.",
            pitch_angle="Large established broker - compliance + risk language. ROI conservative math. Possibly at the upper edge of 'SMB' - verify pre-pitch that they're not enterprise-scale.",
            verification_needed=["md_or_ceo_name", "linkedin_url", "email", "actual_size_range"],
        ),
    },
]


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    with OUTPUT.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS, quoting=csv.QUOTE_ALL)
        writer.writeheader()
        for rec in RECORDS:
            writer.writerow(rec)

    log.info("Wrote %d Tier 3 records to %s", len(RECORDS), OUTPUT)
    log.info("File size: %d bytes", OUTPUT.stat().st_size)
    verified = sum(1 for r in RECORDS if r["LinkedIn URL"])
    tbd = len(RECORDS) - verified
    log.info("Breakdown: %d with LinkedIn verified, %d LinkedIn TBD", verified, tbd)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
