"""
Gmail email sender.

Sends n8n workflow performance report links via Gmail API.
"""

import base64
import json
import sys
from pathlib import Path
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from google_auth import get_google_credentials


class EmailSender:
    """Sends emails via Gmail API."""

    def __init__(self, credentials):
        self.creds = credentials
        self.gmail_service = build('gmail', 'v1', credentials=credentials)

    def send_analytics_report(self, recipient, presentation_url, analysis_summary, subject=None):
        if not subject:
            subject = f"n8n Workflow Performance Report - {datetime.now().strftime('%B %d, %Y')}"

        html_body = self._build_email_html(presentation_url, analysis_summary)
        message = self._create_message(to=recipient, subject=subject, html_body=html_body)

        try:
            sent_message = self.gmail_service.users().messages().send(
                userId='me', body=message
            ).execute()
            message_id = sent_message['id']
            print(f"  Email sent successfully!")
            print(f"  To: {recipient}")
            print(f"  Message ID: {message_id}")
            return message_id
        except HttpError as error:
            print(f"  Gmail API error: {error}")
            raise

    def _build_email_html(self, presentation_url, summary):
        total_workflows = summary.get('total_workflows', 0)
        total_executions = summary.get('total_executions', 0)
        success_rate = summary.get('overall_success_rate', 0)
        active_workflows = summary.get('active_workflows', 0)

        html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }}
        .header {{ background-color: #FF6D5A; color: white; padding: 20px; text-align: center; border-radius: 5px; }}
        .content {{ padding: 20px; background-color: #f9f9f9; border-radius: 5px; margin-top: 20px; }}
        .stats {{ background-color: white; padding: 15px; margin: 15px 0; border-left: 4px solid #FF6D5A; }}
        .stat-item {{ margin: 10px 0; }}
        .stat-label {{ font-weight: bold; color: #666; }}
        .stat-value {{ font-size: 1.3em; color: #FF6D5A; font-weight: bold; }}
        .cta-button {{ display: inline-block; background-color: #FF6D5A; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; margin: 20px 0; font-weight: bold; }}
        .footer {{ text-align: center; color: #666; font-size: 0.9em; margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>n8n Workflow Performance Report</h1>
        <p>Your workflow automation health check</p>
    </div>
    <div class="content">
        <h2>Report Ready!</h2>
        <p>Your n8n workflow performance report has been generated:</p>
        <div class="stats">
            <div class="stat-item"><span class="stat-label">Total Workflows:</span> <span class="stat-value">{total_workflows}</span></div>
            <div class="stat-item"><span class="stat-label">Total Executions:</span> <span class="stat-value">{total_executions:,}</span></div>
            <div class="stat-item"><span class="stat-label">Overall Success Rate:</span> <span class="stat-value">{success_rate:.1f}%</span></div>
            <div class="stat-item"><span class="stat-label">Active Workflows:</span> <span class="stat-value">{active_workflows}</span></div>
        </div>
        <p style="text-align: center;"><a href="{presentation_url}" class="cta-button">View Full Report</a></p>
        <p><strong>The report includes:</strong></p>
        <ul>
            <li>Workflow success rates and reliability scores</li>
            <li>Execution trend analysis over time</li>
            <li>Error pattern detection and failing workflows</li>
            <li>Performance benchmarks and throughput metrics</li>
            <li>Optimization recommendations</li>
        </ul>
    </div>
    <div class="footer">
        <p>Generated by n8n Agentic Workflows Manager</p>
        <p>Report date: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
    </div>
</body>
</html>
"""
        return html

    def _create_message(self, to, subject, html_body):
        message = MIMEMultipart('alternative')
        message['To'] = to
        message['Subject'] = subject

        text_body = f"n8n Workflow Performance Report\n\nYour report is ready!\n\nGenerated on {datetime.now().strftime('%B %d, %Y')}"
        message.attach(MIMEText(text_body, 'plain'))
        message.attach(MIMEText(html_body, 'html'))

        raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode('utf-8')
        return {'raw': raw_message}


def main():
    from config_loader import load_config

    try:
        config = load_config()
        print("Authenticating with Google...")
        creds = get_google_credentials(
            credentials_path=config['google_oauth']['credentials_path'],
            token_path=config['google_oauth']['token_path']
        )

        recipient = config['email'].get('recipient')
        if not recipient or recipient == 'your_email@example.com':
            print("Error: No recipient email configured.")
            sys.exit(1)

        tmp_dir = Path(config['paths']['tmp_dir'])
        presentation_file = tmp_dir / "presentation_info.json"
        analysis_file = tmp_dir / "analysis_results.json"

        if not presentation_file.exists():
            print("Error: presentation_info.json not found.")
            sys.exit(1)

        with open(presentation_file, 'r') as f:
            presentation_info = json.load(f)
        with open(analysis_file, 'r') as f:
            analysis_data = json.load(f)

        presentation_url = presentation_info['presentation_url']
        analysis_summary = analysis_data.get('summary', {})

        subject = config['email'].get('subject')
        if subject and '{date}' in subject:
            subject = subject.replace('{date}', datetime.now().strftime('%B %d, %Y'))

        sender = EmailSender(creds)
        sender.send_analytics_report(
            recipient=recipient, presentation_url=presentation_url,
            analysis_summary=analysis_summary, subject=subject
        )
        print(f"\n  Report delivered to: {recipient}")

    except Exception as e:
        print(f"\nError: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
